# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171203_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='idProducto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Producto'),
        ),
    ]
