# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171203_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(max_length=5)),
                ('mensaje', models.CharField(max_length=80)),
                ('id_multiple', models.CharField(max_length=5)),
            ],
        ),
    ]
