# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0005_auto_20171127_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
