# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_auto_20171127_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
