# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0008_auto_20171127_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
