# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:04
from __future__ import unicode_literals

import apps.proveedor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0011_auto_20171127_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idProveedor',
            field=models.CharField(max_length=50, null=True, verbose_name=apps.proveedor.models.Proveedor),
        ),
    ]
