# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:04
from __future__ import unicode_literals

import apps.proveedor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0012_producto_idproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProveedor',
            field=models.CharField(default=0, max_length=50, verbose_name=apps.proveedor.models.Proveedor),
        ),
    ]
