# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0013_auto_20171127_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProveedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
