# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20171210_0633'),
        ('proveedor', '0017_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='idUsuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.UsuariosTabla'),
            preserve_default=False,
        ),
    ]
