# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0018_proveedor_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
    ]
