# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0022_auto_20171222_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
