# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0023_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
