# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_index=True, max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('id_doc', models.CharField(max_length=10)),
                ('permisos', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('telf', models.CharField(max_length=15)),
                ('domicilio', models.TextField(max_length=15)),
            ],
        ),
    ]
