# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_carritocompras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='idCliente',
        ),
        migrations.DeleteModel(
            name='CarritoCompras',
        ),
    ]
