# Generated by Django 2.0 on 2017-12-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0021_auto_20171211_0554'),
        ('registro', '0006_auto_20171210_2114'),
        ('cliente', '0005_auto_20171211_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_deseos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=10)),
                ('fecha_pedido', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
    ]
