# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0002_auto_20171127_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('idIntermediario', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona')),
            ],
        ),
    ]
