# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20171127_0712'),
        ('intermediario', '0002_auto_20171206_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('idIntermediario', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=0)),
                ('idPersona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona')),
            ],
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
