# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_carritodecompras'),
        ('intermediario', '0003_auto_20171206_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Pedidos')),
            ],
        ),
    ]
