# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20171127_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_index=True, max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('permisos', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('prueba', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='password',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
    ]
