# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_persona_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.UsuariosTabla'),
        ),
    ]
