# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20171210_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariostabla',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
