# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='encargado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='info',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razonSocial',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telf',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
