# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0003_auto_20171127_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(db_index=True, max_length=20, null=True)),
                ('razonSocial', models.CharField(db_index=True, max_length=100, null=True)),
                ('encargado', models.CharField(max_length=100, null=True)),
                ('categoria', models.CharField(max_length=20, null=True)),
                ('telf', models.CharField(max_length=15, null=True)),
                ('domicilio', models.TextField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('info', models.CharField(max_length=300, null=True)),
                ('usuario', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
