# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0015_auto_20171127_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioBasico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='urlImagen',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
