# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0020_auto_20171211_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='info',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='urlImagen',
            field=models.ImageField(upload_to='productosImg'),
        ),
    ]
