# Generated by Django 2.0 on 2017-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0021_auto_20171211_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioBasico',
            field=models.FloatField(default=0),
        ),
    ]
