# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_lista_deseos_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='solicitudes',
            field=models.IntegerField(default=0),
        ),
    ]
